<?php
$files = ['lang/en.json', 'lang/fr.json'];

$newKeysFr = [
    'nav.ferme_bilan' => 'Bilan de la Ferme',
    'ferme_bilan.title' => 'Bilan de la Ferme',
    'ferme_bilan.description' => 'Voici le bilan financier global de la ferme. Il regroupe à la fois les revenus générés par les commissions sur le bénéfice net des autres investisseurs, ainsi que les revenus générés par les investissements directs de la ferme.',
    'ferme_bilan.empty_description' => "Aucune donnée financière n'est disponible pour le moment.",
    'ferme_bilan.global_costs' => 'Coûts Globaux',
    'ferme_bilan.net_milk_revenue' => 'Revenus Lait (Net)',
    'ferme_bilan.sales_revenue' => 'Revenus Vente',
    'ferme_bilan.global_benefit' => 'Bénéfice Global',
    'ferme_bilan.commission_part' => 'Bénéfices via Commissions (Cas 1)',
    'ferme_bilan.investment_part' => 'Bénéfices via Investissements (Cas 2)',
    'ferme_bilan.total_farm_part' => 'Part Totale de la Ferme',
    'admin_cheptel_list.add_modal.purchase_price' => "Prix d'achat (DH)",
    'admin_cheptel_details.purchase_price_label' => "Prix d'achat :",
    'cheptel_details.purchase_price_label' => "Prix d'achat :"
];

$newKeysEn = [
    'nav.ferme_bilan' => 'Farm Financials',
    'ferme_bilan.title' => 'Farm Financials',
    'ferme_bilan.description' => 'Here is the overall financial balance of the farm. It groups both the revenues generated by commissions on the net profit of other investors, and the revenues generated by direct investments of the farm.',
    'ferme_bilan.empty_description' => "No financial data available at the moment.",
    'ferme_bilan.global_costs' => 'Global Costs',
    'ferme_bilan.net_milk_revenue' => 'Net Milk Revenue',
    'ferme_bilan.sales_revenue' => 'Sales Revenue',
    'ferme_bilan.global_benefit' => 'Global Benefit',
    'ferme_bilan.commission_part' => 'Benefits via Commissions (Case 1)',
    'ferme_bilan.investment_part' => 'Benefits via Investments (Case 2)',
    'ferme_bilan.total_farm_part' => 'Total Farm Part',
    'admin_cheptel_list.add_modal.purchase_price' => 'Purchase Price (DH)',
    'admin_cheptel_details.purchase_price_label' => 'Purchase Price :',
    'cheptel_details.purchase_price_label' => 'Purchase Price :'
];

foreach ($files as $file) {
    $content = json_decode(file_get_contents($file), true);
    $lang = (strpos($file, 'fr.json') !== false) ? 'fr' : 'en';
    $keys = ($lang === 'fr') ? $newKeysFr : $newKeysEn;
    
    foreach ($keys as $dotKey => $value) {
        $parts = explode('.', $dotKey);
        $temp = &$content;
        foreach ($parts as $part) {
            if (!isset($temp[$part])) {
                $temp[$part] = [];
            }
            $temp = &$temp[$part];
        }
        $temp = $value;
        unset($temp);
    }
    
    file_put_contents($file, json_encode($content, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
}
echo "Translations updated.\n";
